apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    url: ${DB_HOST}:${DB_PORT}
    database: ${DB_NAME}
    user: ${DB_USER}
    secureJsonData:
      password: ${DB_PASSWORD}
    jsonData:
      sslmode: "require" # Neon.tech requires SSL
      postgresVersion: 1500 # Approx version
    isDefault: true
    editable: false
