apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    uid: P8E80F9AE52D32594
    url: ${DB_HOST}:${DB_PORT}
    database: ${DB_NAME}
    user: ${DB_USER}
    secureJsonData:
      password: ${DB_PASSWORD}
    jsonData:
      sslmode: "require" 
      postgresVersion: 1500 
    isDefault: true
    editable: false
